---
- name: Set up Apache server with Hello World page
  hosts: all
  become: yes

  tasks:

    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create index.html with Hello World
      copy:
        content: "<html><body><h1>Hello World the lab is done</h1></body></html>"
        dest: /var/www/html/index.html
        mode: '0644' 
