---
- name: Install and Configure Apache
  hosts: webservers
  become: yes
  become_user: root

  tasks:
  - name: Update APT Cache
    apt:
      update_cache: yes
      force_apt_get: yes

  - name: Remove apt lock file
    file:
      state: absent
      path: "/var/lib/dpkg/lock"

  - name: Wait for sudo
    become: yes
    shell: |
      set timeout 300
      while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;
  
  - name: Install Apache
    apt:
      name: apache2
      state: latest

  - name: Remove the existing index.html
    file:
      path: /var/www/html/index.html
      force: yes
      state: absent

  - name: Create a new empty index.html file
    file:
      path: /var/www/html/index.html
      state: touch
      owner: root
      group: root
      mode: 0755

  - name: Add content to the index.html file
    lineinfile:
      path: /var/www/html/index.html
      line: Hello Ansible World!   LAB OF TERRAFORM!!!!!

  - name: Enable service and start service
    service:
      name: apache2
      enabled: yes
      state: started
