---
- name: Test the website
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Check port 80 is listening on managed node
      wait_for:
        port: 80
        state: started
        timeout: 3

    - name: Verify apache is available remotely
      uri:
        url: http://{{ inventory_hostname }}/index.html
      delegate_to: localhost

    - name: Stat apache2
      stat:
        path: /usr/sbin/apache2
      register: s

    - name: Fail if apache2 doesn't exist
      assert:
        that:
          - s.stat.exists
        fail_msg: "/usr/sbin/apache2 does not exist"
        success_msg: "/usr/sbin/apache2 exists"

    - name: Verify apache2 is enabled
      shell: systemctl list-unit-files | grep apache2.service | awk -F ' ' '{print $2}'
      register: c

    - name: Fail if apache2 is not enabled
      assert:
        that:
          - "'enabled' in c.stdout"
        fail_msg: "apache2 service is not enabled"
        success_msg: "apache2 service is enabled"

    - name: Stat index.html
      stat:
        path: /var/www/html/index.html
      register: u

    - name: Confirm that index.html exists & is owned by root
      assert:
        that:
          - u.stat.exists
          - u.stat.pw_name == "root"
        fail_msg: "index.html may not exist or have correct ownership"
        success_msg: "index.html exists with proper ownership"

    - name: Stat vars.html
      stat:
        path: /var/www/html/vars.html
      register: v

    - name: Confirm that vars.html exists & is owned by root
      assert:
        that:
          - v.stat.exists
          - v.stat.pw_name == "root"
        fail_msg: "vars.html may not exist or have correct ownership"
        success_msg: "vars.html exists with proper ownership"
